version: '2'
services:

  metabase:
    restart: always
    image: metabase/metabase:v0.46.5
    container_name: metabase
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    ports:
      - "3030:3000"
    volumes:
      - "${LOCAL_DOCKER_VOLUMES}${DATA_METABASE}:/metabase-data"

networks:
  default:
    external:
      name: local-sandbox-networks