version: '2'
services:

  postgre:
    restart: always
    image: ${IMAGE_POSTGRE}
    container_name: postgre
    user: root
    volumes:
      - "${LOCAL_DOCKER_VOLUMES}${DATA_POSTGRE_DATA}:/var/lib/postgresql/data"
      - "${LOCAL_DOCKER_VOLUMES}${DATA_POSTGRE_LOGS}:/var/log/postgresql"
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"

  pgadmin4:
    restart: always
    image: dpage/pgadmin4:7.4
    container_name: pgadmin4
    user: root
    ports:
      - "5454:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=default@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes: 
      - "${LOCAL_DOCKER_VOLUMES}${DATA_PGADMIN4}:/var/lib/pgadmin"
    depends_on: 
      - postgre

networks:
  default:
    external:
      name: local-sandbox-networks

volumes:
  postgres_data:
    external: true
  postgres_logs:
    external: true
