version: '2'
services:

  zookeeper:
    restart: always
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    restart: always
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - "29092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:29092,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  # mirrormaker:
  #   image: zeelos/kafka-mirrormaker:5.2.2
  #   container_name: mirrormaker
  #   depends_on:
  #     - kafka
  #   environment:
  #     #MIRRORMAKER_WHITE_LIST: 'topic-1,topic-2'
  #     MIRRORMAKER_OFFSET_COMMIT_INTERVAL: 60000
  #     MIRRORMAKER_NUM_STREAMS: 1
  #     CONSUMER_BOOTSTRAP_SERVERS: 'SOURCE_BROKER_IP_ADDRESS:PORT'  # set actual values
  #     CONSUMER_GROUP_ID: 'mirrormaker-to-local-${MIRRORMAKER_CONSUMER_GROUP_TAG}'  # every time when kafka.sh is called it generates different tag
  #     CONSUMER_AUTO_OFFSET_RESET: latest
  #     PRODUCER_BOOTSTRAP_SERVERS: kafka:29092

networks:
  default:
    external:
      name: local-sandbox-networks