version: '2'
services:

  web:
    restart: always
    image: dockers-web:latest
    ports:
      - "8888:80"
      - "3443:443"
    # volumes:
    #   - /tmp/config/web/nginx:/etc/nginx
    #   - /tmp/config/web/ssl:/etc/ssl/private

networks:
  default:
    external:
      name: local-sandbox-networks